name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    # Use macOS runner for hardware acceleration
    runs-on: macos-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (since you're using JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up Android SDK with appropriate API and build tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # Step 4: Cache Gradle dependencies for faster builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: Grant execute permissions to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 6: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true

      # Step 7: Start the emulator and run UI tests
      - name: Start emulator and run UI tests
        uses: reactivecircus/android-emulator-runner@v2.32.0
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          profile: Nexus 6
          emulator-options: -no-window -no-snapshot
          script: ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.systemProperty=IS_TESTING=true
