name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0

      - name: Build Debug APK
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run Instrumentation Tests on Firebase Test Lab
        uses: wzieba/FirebaseTestLab@v2
        with:
          project: ${{ secrets.FIREBASE_PROJECT_ID }}
          serviceCredentialsJson: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          debugApk: app/build/outputs/apk/debug/app-debug.apk
          testApk: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
