name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK and Instrumentation Test APK
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run Instrumentation Tests on Firebase Test Lab
        uses: wzieba/FirebaseTestLab@v2
        with:
          project: ${{ env.FIREBASE_PROJECT_ID }}
          serviceCredentialsFileContents: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          appApk: app/build/outputs/apk/debug/app-debug.apk
          testApk: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          deviceIds: Nexus6P
          apiLevel: 27
          locales: en
          orientations: portrait
